### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by mueller-ma**
Two questions:
Translation or Translations?
Can you give me a synonym for Carpentry? I dont find a good translation

### CODE REVIEW

**Comment by subchannel13** [comment]
About Translation or Translations, good question. English is not my native language and internet says both are good and some games list people under "Localization". There is French translation being made so there will be multiple entries but I think I'll go with singular "Translation by" after all.

About carpentry, it's a craft of shaping building materials during construction. It's sometimes synonymous with woodwork but here the context leans more to construction. Now that I think of it "masonry" would be better term.

**Comment by mueller-ma** [comment]
You can merge this now. Can you squash the commits?

**Comment by subchannel13** [comment]
Yes, I can squash them. I'd like to list you in "about" screen under "Translation by" section. Do you want to be mentioned by some other name than "mueller-ma"?

**Comment by mueller-ma** [comment]
mueller-ma

**Comment by subchannel13** [comment]
Added. Now I see helpText (the biggest text entry :)) is untranslated, oh well...

**Comment by mueller-ma** [comment]
I translate it when I have time for that :)

**Pull request merged**
