### PR TITLE
Optimize image sizes

### PR DESCRIPTION
**Pull request by TPS**
@subchannel13 I noticed that the F-Droid-built APK recently increased in size 10×.  This is a quick-&-simple effort to help with that.  Since [ImgBot](https://ImgBot.net) is free for open-source, maybe y'all should [signup](https://github.com/marketplace/imgbot) to have it maintain automatically?

### CODE REVIEW

**Comment by subchannel13** [comment]
Thank you for PR! I'll check ImgBot out, first time I've heard about it.

The reason APK size increased was adding androidx.appcompat dependency (part of night mode feature). I did it with a heavy hearth but at least it help me sort out other legacy Android support issues. Images in your PR do shave of ~10 kB out of 1200 kB so it won't change the size that much but it doesn't hurt :).

**Comment by subchannel13** [comment]
I've reviewed PR changes, images looks unchanged. There seems to be very slight color brightness change but in production it should be next to unnoticeable since those images cover very little screen space.

One thing I'd ask you to change is to remove changes to images in fastlane/metadata/android/en-US/images/phoneScreenshots/ folder. Those images are for F-Droid store and are not built in APK.

**Comment by TPS** [comment]
The screenshots might be as important to optimize, as they're presumably downloaded @ least as often as the APKs.

**Comment by subchannel13** [comment]
That is an assumption we cannot check due to lack of analytics. It doesn't hurt anyway so I'll merge PR. Under which name do you want to be credited in game's "about" section?

**Comment by TPS** [comment]
@subchannel13 I'd prefer you give credit to @dabutvin, who's the lead/coordinating dev on [ImgBot](https://github.com/dabutvin).  If you feel the _need_ to mention me anyway, @TPS is just fine.

**Pull request merged**
