### PR TITLE
Update translation files

### PR DESCRIPTION
**Pull request by xinxinxinxinxin**
I update tranlation files with the last changes in strings.xml.
Next time, can you update that files when you add new content to strings.xml?

### CODE REVIEW

**Comment by mueller-ma** [comment]
Here is the real german translation. Is there a typo in banishProgress? Shouldn't it be "their power"?

+    <string name="gatesClosed">%1d Höllentore geschlossen</string>
+    <string name="gatesOpened">, Dämonen öffneten %1d</string>
+    <string name="gatesLeft">%1d Höllentore</string>
+    <string name="difficultyStartingPop">Population bei Spielstart: %1s</string>
+    <string name="difficultyDemonSpawn">Dämonen Spawn-Rate: %1s</string>
+    <string name="difficultyDemonGrowth">Dämonenstärkezuwachs: %1s</string>
+    <string name="banishNever">hoffnungslos</string>
+    <string name="banishSlow">für immer</string>
+    <string name="scoresTitle">Bestenliste</string>
+    <string name="scoresTurns">Runden</string>
+    <string name="scoredDifficulty">Schwierigkeitsgrad</string>
+    <string name="scoresButton">Bestenliste</string>
+    <string name="banishProgress">Wissenschaftler vollziehen Verbannungsrituale und Dämonen versuchen ihre Stärke zu erhöhen. Dämonenstärke ist jetzt bei %1d.</string>
+    <string name="banishProgressShort">Dämonenstärke ist jetzt bei %1d.</string>

**Comment by subchannel13** [comment]
Yeah, that's a typo, will correct.

**Comment by subchannel13** [comment]
Thanks for PR!

**Comment by mueller-ma** [comment]
@subchannel13 The German strings file is actually english.

**Comment by subchannel13** [comment]
I've noticed it later and removed them.

**Comment by mueller-ma** [comment]
Not in the german strings file. Can you include the strings I posted previously here?

**Comment by subchannel13** [comment]
Ah, there was no actual translations in XMLs. Yeah, I saw it in `-fr` but didn't checked `-de`. Your nicely colored and formatted comment made me think it was `values-de/strings.xml` content, not actual comment.

@xinxinxinxinxin What was the idea behind RP? Missing translations should fallback to default entries.

**Comment by mueller-ma** [comment]
It's easier for people without Android Studio to find missing translations.

**Comment by subchannel13** [comment]
Ah, I see. In future I'll have to turn down such PR's because false translation is worse then no translation. Fake translations are harder to spot in Android Studio translation editor and lint doesn't report them. People without Android Studio should solve a tool problem on their their side, not muddy the content. For example, Notepad++ can open two files side by side and synchronize scrolling which make it easy to find differing and missing lines.

**Comment by xinxinxinxinxin** [comment]
In other Android softwares I translate, all strings.xml are updated when content is added. So I just have to open values-fr/strings.xml and translate english sentences.

**Comment by subchannel13** [comment]
On this project I'm against that practice. I deem it wrong solution for a problem outside of this project.

**Comment by subchannel13** [comment]
How about compromise, to put untranslated entries as a XML comments instead?
`<!-- <string name="someKey"></string> -->`

This would not interfere with proper development tools and it's easy to find especially with any editors that support XML syntax highlighting.

**Pull request merged**
