### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by mueller-ma**

### CODE REVIEW

**Comment by subchannel13** [comment]
Thank you for pull request! I'd prefer to merge it with current development branch "v1.2" instead with master. I've added a few more entries to the strings.xml to cover future feature and updated "aboutText" to credit translation contributors.

Speaking of which, under which name would you like to be credited as?

**Comment by mueller-ma** [comment]
Can you split "aboutText" in several strings per line.
Example "Developed by"+"Ivan Kravarščan"+"Translation:"+"German by"+"xxx"+"French by"+"xxx"

Than you can set all names and URLs to nontranslatable

**Comment by subchannel13** [comment]
Good idea, will make it so.

**Comment by mueller-ma** [comment]
Closing for now

**Pull request closed without merging**
